runtime: python37

handlers:
- url: /ikea
  static_files: index.html
  upload: index.html

- url: /ikea/
  static_files: index.html
  upload: index.html

- url: /ikea/(.*)
  static_files: \1
  upload: (.*)
