runtime: python37

handlers:
- url: /ikea
  static_files: ikea/index.html
  upload: ikea/index.html

- url: /ikea/
  static_files: ikea/index.html
  upload: ikea/index.html

- url: /ikea/(.*)
  static_files: ikea/\1
  upload: ikea/(.*)
